-- localsend_i18n.lua — LocalSend plugin
-- Translation loader.
--
-- DESIGN (isolated proxy, no global monkey-patch)
-- =================================================
-- KOReader's bundled gettext is single-textdomain and only knows about the
-- strings compiled into the core koreader.pot/koreader.mo. A third-party,
-- OTA-distributed plugin like LocalSend cannot get its strings into that core
-- catalogue, so we ship our own flat locale/<lang>.po files and parse them
-- here.
--
-- The loader never touches package.loaded["gettext"] and never mutates the
-- global GetText module's fields. Replacing/wrapping the global module breaks
-- other plugins that load their own .po files (writes land on the wrapper and
-- never reach the native module). Instead we export a self-contained
-- translate() / ngettext() pair that main.lua assigns to its local `_` / `N_`
-- and injects into the submodules via the existing deps table — so the
-- submodules need no changes at all.
--
-- Strings not found in LocalSend's .po files fall through to the native
-- KOReader gettext, so shared UI words (that happen to exist in both) still
-- translate correctly.
--
-- Public API:
--   local I18n = require("localsend_i18n")
--   local _    = I18n.translate   -- replaces: local _ = require("gettext")
--   local N_   = I18n.ngettext    -- replaces: local N_ = _.ngettext
--   I18n.getLang()                -- current detected language
--   I18n.reset()                  -- clears cached translations (lang change)
--
-- HOW TO ADD A LANGUAGE
--   1. Copy locale/localsend.pot -> locale/<lang>.po  (e.g. locale/pt_PT.po)
--   2. Fill in the msgstr values.
--   3. Done — no code changes needed.

local logger = require("logger")

-- Locate the plugin directory from this file's own path. On-device the plugin
-- layout is flat (_meta.lua, main.lua, localsend_i18n.lua, locale/, ...) so the
-- directory holding this module is the plugin root and locale/ sits beside it.
local _dir = (debug.getinfo(1, "S").source:match("^@(.+/)") or "./")

-- ---------------------------------------------------------------------------
-- .po parser — minimal, handles the subset generated by locale/localsend.pot.
-- Supports msgid / msgid_plural / msgstr[N], multiline continuations, escape
-- sequences, and the Plural-Forms header.
-- ---------------------------------------------------------------------------
-- Convert a C-style ternary "c ? a : b" to the Lua idiom
-- "(c and (a) or (b))", recursing into nested ternaries. Plural-form branches
-- are always integer literals in real catalogs, so the and/or idiom is safe
-- (0 is truthy in Lua, unlike most languages).
local function ternaryToLua(s)
    local function findQuestion(str)
        local depth = 0
        for i = 1, #str do
            local c = str:sub(i, i)
            if c == "(" then
                depth = depth + 1
            elseif c == ")" then
                depth = depth - 1
            elseif c == "?" and depth == 0 then
                return i
            end
        end
        return nil
    end

    local q = findQuestion(s)
    if not q then
        return s
    end

    local depth = 0
    local colon = nil
    for i = q + 1, #s do
        local c = s:sub(i, i)
        if c == "(" then
            depth = depth + 1
        elseif c == ")" then
            depth = depth - 1
        elseif c == ":" and depth == 0 then
            colon = i
            break
        end
    end

    if not colon then
        return s
    end

    local cond = s:sub(1, q - 1)
    local truthy = s:sub(q + 1, colon - 1)
    local falsy = s:sub(colon + 1)
    return "(" .. ternaryToLua(cond) .. " and (" .. ternaryToLua(truthy) .. ") or (" .. ternaryToLua(falsy) .. "))"
end

-- Compile a gettext Plural-Forms header value to a function(n) -> integer
-- plural index. Accepts the full header value, e.g.
--   "nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);"
-- and handles both predicate forms ("plural=(n != 1)") and full C ternary
-- forms (Polish/Russian/etc.). Returns nil if it cannot be compiled, in which
-- case ngettext() falls back to the n==1 ? singular : plural default (correct
-- for English/Portuguese-style 2-form languages).
local function compilePluralForm(plural_forms)
    if type(plural_forms) ~= "string" then
        return nil
    end
    -- Capture just the "plural=(...)" clause. %b() matches balanced parens, so
    -- ternary bodies with inner grouping come out whole.
    local expr = plural_forms:match("plural=(%b())")
    if not expr then
        -- Some catalogs omit the wrapping parens: "plural=n != 1;"
        expr = plural_forms:match("plural=([^;]+)")
    end
    if not expr or expr == "" then
        return nil
    end
    expr = expr:gsub("^%(", ""):gsub("%)$", "") -- strip wrapping parens

    -- Normalise C operators to Lua.
    expr = expr:gsub("!=", "~=")
    expr = expr:gsub("&&", " and ")
    expr = expr:gsub("%|%|", " or ")
    expr = expr:gsub("!([^=])", "not %1") -- bare logical not (after != handled)

    local body
    if expr:find("?", 1, true) then
        body = "return " .. ternaryToLua(expr)
    else
        -- Pure predicate (e.g. "n ~= 1"): coerce the boolean to a 0/1 index.
        body = "return (" .. expr .. ") and 1 or 0"
    end

    local loader = loadstring or load
    local fn = loader("return function(n) " .. body .. " end")
    if not fn then
        return nil
    end

    local ok, plural_fn = pcall(fn)
    if not ok or type(plural_fn) ~= "function" then
        return nil
    end
    -- Guard: a malformed expression that compiles but returns a non-number
    -- would index the msgstr[] table with the wrong key type.
    if type(plural_fn(1)) ~= "number" then
        return nil
    end
    return plural_fn
end

local function parsePO(path)
    local f = io.open(path, "r")
    if not f then
        return nil
    end

    local map = {}
    local pluralizer = nil
    local entry = { msgid = nil, msgid_plural = nil, msgstrs = {} }
    local current_field = nil

    local function flush()
        if not entry.msgid then
            entry = { msgid = nil, msgid_plural = nil, msgstrs = {} }
            current_field = nil
            return
        end

        if entry.msgid == "" then
            -- The empty-msgid entry holds the file header. Pull Plural-Forms
            -- out of it so ngettext() can pick the right form per language.
            local header = entry.msgstrs[0] or ""
            for line in header:gmatch("([^\n]*)\n?") do
                local plural_line = line:match("^Plural%-Forms:%s*(.-)%s*$")
                if plural_line then
                    pluralizer = compilePluralForm(plural_line)
                    break
                end
            end
        else
            if entry.msgid_plural then
                local trans = {}
                for idx, str in pairs(entry.msgstrs) do
                    if str and str ~= "" then
                        trans[idx] = str
                    end
                end
                if next(trans) then
                    map[entry.msgid] = trans
                end
            else
                local str = entry.msgstrs[0]
                if str and str ~= "" then
                    map[entry.msgid] = str
                end
            end
        end

        entry = { msgid = nil, msgid_plural = nil, msgstrs = {} }
        current_field = nil
    end

    local function unescape(s)
        return s:gsub("\\n", "\n"):gsub("\\t", "\t"):gsub('\\"', '"'):gsub("\\\\", "\\")
    end

    for line in f:lines() do
        local text = line:match("^%s*(.-)%s*$")
        if text == "" then
            flush()
        -- Comment lines ("^#") match none of the branches below and are skipped.
        elseif text:match('^msgid%s+"') then
            flush()
            entry.msgid = unescape(text:match('^msgid%s+"(.*)"') or "")
            current_field = "msgid"
        elseif text:match('^msgid_plural%s+"') then
            entry.msgid_plural = unescape(text:match('^msgid_plural%s+"(.*)"') or "")
            current_field = "msgid_plural"
        elseif text:match('^msgstr%[%d+%]%s+"') then
            local idx = tonumber(text:match('^msgstr%[(%d+)%]%s+"'))
            entry.msgstrs[idx] = unescape(text:match('^msgstr%[%d+%]%s+"(.*)"') or "")
            current_field = "msgstr" .. idx
        elseif text:match('^msgstr%s+"') then
            entry.msgstrs[0] = unescape(text:match('^msgstr%s+"(.*)"') or "")
            current_field = "msgstr0"
        elseif text:match('^"') and current_field then
            local cont = unescape(text:match('^"(.*)"') or "")
            if current_field == "msgid" then
                entry.msgid = entry.msgid .. cont
            elseif current_field == "msgid_plural" then
                entry.msgid_plural = entry.msgid_plural .. cont
            else
                local idx = tonumber(current_field:match("^msgstr(%d+)$"))
                if idx then
                    entry.msgstrs[idx] = (entry.msgstrs[idx] or "") .. cont
                end
            end
        end
    end
    flush()
    f:close()
    return map, pluralizer
end

-- ---------------------------------------------------------------------------
-- Language detection.
-- G_reader_settings:readSetting("language") is the KOReader UI language the
-- user picked; fall back to the C locale env vars if unset (e.g. headless
-- tests).
-- ---------------------------------------------------------------------------
local function detectLang()
    local lang = G_reader_settings and G_reader_settings:readSetting("language")
    if type(lang) == "string" and lang ~= "" then
        return lang
    end
    local lc = os.getenv("LANG") or os.getenv("LC_ALL") or os.getenv("LC_MESSAGES") or ""
    lang = lc:match("^([a-zA-Z_]+)")
    return lang or "en"
end

-- ---------------------------------------------------------------------------
-- Load translation table (lazy, cached).
-- Tries the full locale (pt_PT) then falls back to the language prefix (pt).
-- ---------------------------------------------------------------------------
local _translations = nil
local _loaded = false

local function loadTranslations()
    if _loaded then
        return _translations
    end
    _loaded = true

    local lang = detectLang()
    if lang == "en" or lang:match("^en_") then
        return nil
    end

    local function try(name)
        local path = _dir .. "locale/" .. name .. ".po"
        local entries, pluralizer = parsePO(path)
        if entries and next(entries) then
            local n = 0
            for _ in pairs(entries) do
                n = n + 1
            end
            logger.info("localsend i18n: loaded " .. path .. " — " .. n .. " strings")
            return { entries = entries, plural = pluralizer }
        end
    end

    _translations = try(lang)
        or (function()
            local prefix = lang:match("^([a-zA-Z]+)")
            if prefix and prefix ~= lang then
                return try(prefix)
            end
        end)()

    return _translations
end

-- ---------------------------------------------------------------------------
-- Core translation functions.
--
-- main.lua does:
--   local I18n = require("localsend_i18n")
--   local _  = I18n.translate
--   local N_ = I18n.ngettext
-- and injects _ / N_ into every submodule via the deps table.
--
-- Strings absent from LocalSend's catalogue fall through to the native
-- KOReader gettext without writing to or wrapping package.loaded["gettext"].
-- ---------------------------------------------------------------------------

local function translate(msgid)
    local t = loadTranslations()
    if t then
        local entry = t.entries[msgid]
        if type(entry) == "string" then
            return entry
        elseif type(entry) == "table" then
            -- Plural entry used with plain translate(): return the singular form.
            return entry[0] or entry[1] or msgid
        end
    end
    -- Read-only access to native gettext — no writes, no state mutation.
    local ok, gt = pcall(require, "gettext")
    if ok and gt then
        return gt(msgid)
    end
    return msgid
end

local function ngettext(msgid, msgid_plural, n)
    local t = loadTranslations()
    if t then
        local entry = t.entries[msgid]
        if type(entry) == "table" then
            local idx
            if t.plural then
                idx = t.plural(n) or 0
            else
                idx = (n == 1) and 0 or 1
            end
            local translated = entry[idx]
            if translated then
                return translated
            end
        elseif type(entry) == "string" and n == 1 then
            return entry
        end
    end
    -- Fall through to native gettext.
    local ok, gt = pcall(require, "gettext")
    if ok and gt then
        if type(gt) == "table" and type(gt.ngettext) == "function" then
            return gt.ngettext(msgid, msgid_plural, n)
        end
        local fallback = (n == 1) and msgid or msgid_plural
        return gt(fallback)
    end
    return (n == 1) and msgid or msgid_plural
end

-- ---------------------------------------------------------------------------
-- reset() — clears cached translations. Call after the user changes the UI
-- language so the next translate() re-reads the right .po file.
-- ---------------------------------------------------------------------------
local function reset()
    _translations = nil
    _loaded = false
    logger.info("localsend i18n: translation cache cleared")
end

return {
    translate = translate,
    ngettext = ngettext,
    getLang = detectLang,
    reset = reset,
}
